django_photo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'photo/upload/', include(('photo.urls', 'photo'), namespace='photo_upload')),
]

photo/urls.py
from django.conf.urls import url

from photo.views import UploadPhotoApiView

urlpatterns = [
    url(r'import/', UploadPhotoApiView.as_view(), name='import'),
]

photo/models.py
from django.db import models


class Photo(models.Model):
    image = models.ImageField(upload_to="uploads")

photo/views.py
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.response import Response
from rest_framework.views import APIView
from photo.models import Photo
from photo.serializers import UploadSerializer


class UploadPhotoApiView(APIView):
    pareser_classes = (MultiPartParser, FormParser)
    serializer_class = UploadSerializer

    def post(self, request, format=None):
        upload = self.serializer_class(data=request.FILES)

        if upload.is_valid():
            image = Photo(image=upload.validated_data['image'])
            image.save()
            return Response({'success': 'Imported successfully'})
        else:
            return Response(upload.errors, status=400)

templates/photo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/photo/upload.html
{% extends "index.html" %}
{% block content %}
    <div class="widget">
        <div class="widget-heading clearfix">
            <h3 class="widget-title pull-left list-inline">CSV </h3>
            <button type="button" class="btn btn-primary pull-right"><i class="ti-upload mr-5"></i> Загрузить</button>
        </div>
        <div class="widget-body">
            <form id="type-dz" class="dropzone" method="post">{% csrf_token %}</form>
        </div>
    </div>

{% endblock %}
{% block js %}
    <script type="text/javascript">
        $("#type-dz").dropzone({
            url: "{% url 'photo_upload:import' %}",
            paramName: "import",
            acceptedFiles: ".csv",
            maxFilesize: 2,
            maxThumbnailFilesize: .5,
            thumbnailWidth: "250",
            thumbnailHeight: "250",
            dictDefaultMessage: "<i class='icon-dz fa fa-file-text-o'></i>Перетащите сюда файлы для загрузки"
        });
    </script>
{% endblock %}